routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminMainController;
use App\Http\Controllers\AdminProductController;
use App\Http\Controllers\AdminCategoryController;
use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\OrderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth', 'user.check'])->group(function () {
    Route::get('/{category_id?}', [ProductController::class, 'index'])->name('products')->where('category_id', '[0-9]+');
    Route::post('/products/search', [ProductController::class, 'search'])->name('products.search');

    Route::prefix('profile')->group(
        function () {
                Route::get('/', [UserController::class, 'profile'])->name('profile');
                Route::post('/update', [UserController::class, 'update'])->name('profile.update');
            }
    );

    Route::prefix('cart')->group(
        function () {
                Route::get('/', [CartController::class, 'index'])
                    ->name('cart')->middleware('cart.exist');

                Route::post('/add', [CartController::class, 'add'])
                    ->name('cart.add');
            }
    );

    Route::prefix('order')->group(
        function () {
            Route::get('/', [OrderController::class, 'index'])
                ->name('order')->middleware('cart.exist');
            Route::post('/pay', [OrderController::class, 'pay'])
                ->name('order.pay')->middleware('cart.exist');
            Route::get('/thankyou/{order}', [OrderController::class, 'thankyou'])
                ->name('order.thankyou');
            Route::get('/invoice_pdf', [OrderController::class, 'invoicePdf'])
                ->name('order.invoicepdf')->middleware('cart.exist');
        }
    );
});

Route::middleware(['auth', 'admin.check'])->group(function () {
    Route::prefix('admin')->group(
        function () {
            Route::get('/', [AdminMainController::class, 'index'])->name('admin');
            Route::resource('products', AdminProductController::class);
            Route::resource('categories', AdminCategoryController::class);
            Route::resource('users', AdminUserController::class);
        }
    );
});

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Category;
use Carbon\Carbon;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'products';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'price', 'quantity', 'category_id'];

    public function category()
    {
        return $this->belongsTo(Category::class, "category_id", "id");
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format("Y-m-d");
    }
}

app/Http/Controllers/AdminUserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\UserService;
use App\Services\LangService;
use App\Http\Requests\UserUpdateRequest;
use App\Http\Requests\UserStoreRequest;
use App\Models\User;

class AdminUserController extends Controller
{
    public function __construct(UserService $users, LangService $langs)
    {
        $this->users = $users;
        $this->langs = $langs;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view(
            'admin_user.index',
            ["users" => $this->users->getAllNotAdmins()]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view(
            'admin_user.create',
            [
                "langs" => $this->langs->all()
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request)
    {
        $user = $this->users->create($request->all());
        return redirect()->route('users.show', ["user" => $user->id])->withSuccess(
            'User #' . $user->id . " was created!"
        );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view(
            'admin_user.show',
            ["user" => $this->users->findById($id)]
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view(
            'admin_user.edit',
            [
                "user" => $this->users->findById($id),
                "langs" => $this->langs->all()
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        $this->users->update($user->id, $request->except(['_method', '_token']));
        return redirect()->route('users.show', ["user" => $user->id])->withSuccess(
            'User #' . $user->id . " was updated!"
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->users->destroy($id);
        return redirect()->route('users.index')->withSuccess('User #' . $id . " was deleted!");
    }
}

resources/views/admin_user/create.blade.php
@extends('adminlte::page')

@section('content')
    <form method="POST" action="{{ route('users.store') }}">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create new user</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                                    title="Collapse">
                                <i class="fas fa-minus"></i></button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="inputName">Name</label>
                            <input type="text" name="name" id="inputName" class="form-control @error('name') is-invalid @enderror" value="{{old('name')}}">
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="price">Email</label>
                            <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @enderror" value="{{old('email') }}">
                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="inputStatus">Lang</label>
                            <select name="lang" class="form-control custom-select @error('lang') is-invalid @enderror">
                                <option value="">Select Lang</option>
                                @foreach($langs as $lang)
                                    <option @if(old('lang') && $lang->short_name == old('lang'))
                                                selected
                                            @endif
                                            value="{{ $lang->short_name }}">{{ $lang->full_name }}</option>
                                @endforeach
                            </select>
                            @error('lang')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="inputStatus">Status</label>
                            <select name="status" class="form-control custom-select @error('status') is-invalid @enderror">
                                <option @if(old('status') && "active" == old('status'))
                                        selected
                                        @endif
                                        value="active">Active</option>
                                <option @if(old('lang') && "not active" == old('status'))
                                        selected
                                        @endif
                                        value="not active">Not Active</option>
                            </select>
                            @error('status')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password" id="password" class="form-control @error('password') is-invalid @enderror" value="">
                            @error('password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="password">Confirm Password</label>
                            <input type="password" name="password_confirmation" id="password_confirmation" class="form-control @error('password_confirmation') is-invalid @enderror" value="">
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <a href="#" class="btn btn-secondary">Cancel</a>
                <input type="submit" value="Create" class="btn btn-success float-right">
            </div>
        </div>
    </form>
@stop

@section('js')
@stop

resources/views/admin_user/edit.blade.php
@extends('adminlte::page')

@section('content')
    <form method="POST" action="{{ route('users.update', ["user" => $user->id]) }}">
        @method('PUT')
        @csrf
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Users Data</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                                    title="Collapse">
                                <i class="fas fa-minus"></i></button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="inputName">Name</label>
                            <input type="text" name="name" id="inputName" class="form-control @error('name') is-invalid @enderror" value="{{old('name') ?? $user->name }}">
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="price">Email</label>
                            <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @enderror" value="{{old('email') ?? $user->email }}">
                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="inputStatus">Lang</label>
                            <select name="lang" class="form-control custom-select @error('lang') is-invalid @enderror">
                                <option value="">Select Lang</option>
                                @foreach($langs as $lang)
                                    <option @if(old('lang') && $lang->short_name == old('lang'))
                                                selected
                                            @elseif( empty(old('lang')) && $lang->short_name === $user->lang->short_name)
                                                selected
                                            @endif
                                            value="{{ $lang->short_name }}">{{ $lang->full_name }}</option>
                                @endforeach
                            </select>
                            @error('lang')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="inputStatus">Status</label>
                            <select name="status" class="form-control custom-select @error('status') is-invalid @enderror">
                                <option @if(old('status') && "active" == old('status'))
                                        selected
                                        @elseif( empty(old('status')) && "active" === $user->status)
                                        selected
                                        @endif
                                        value="active">Active</option>
                                <option @if(old('lang') && "not active" == old('status'))
                                        selected
                                        @elseif( empty(old('lang')) && "not active" === $user->status)
                                        selected
                                        @endif
                                        value="not active">Not Active</option>
                            </select>
                            @error('status')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <a href="#" class="btn btn-secondary">Cancel</a>
                <input type="submit" value="Save Changes" class="btn btn-success float-right">
            </div>
        </div>
    </form>
@stop

@section('js')
@stop

resources/views/admin_user/index.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        @include('partials.alerts')
        <table id="users" class="table table-bordered table-hover dataTable" role="grid"
               aria-describedby="example2_info">
            <thead>
            <tr role="row">
                <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                    aria-sort="ascending">Name
                </th>
                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Email
                </th>
                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Status
                </th>
                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Lang
                </th>
                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Actions
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
            <tr role="row">
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->status }}</td>
                <td>
                    {{$user->lang->full_name}}
                </td>
                <td>
                    <a class="btn btn-primary btn-sm w-50" href="{{ route('users.show', ["user" => $user->id]) }}">
                        <i class="fas fa-folder">
                        </i>
                        View
                    </a> <br>
                    <a class="btn btn-info btn-sm w-50" href="{{ route('users.edit', ["user" => $user->id]) }}">
                        <i class="fas fa-pencil-alt">
                        </i>
                        Edit
                    </a>
                    <form method="POST" action="{{ route('users.destroy', ["user" => $user->id]) }}">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-danger btn-sm w-50">
                            <i class="fas fa-trash">
                            </i>
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
            @endforeach
            </tbody>
            <tfoot>
        </table>
    </div>
@stop

@section('js')
    <script>
        $(function () {
            $('#users').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });
    </script>
@stop

resources/views/admin_user/show.blade.php
@extends('adminlte::page')

@section('content')
    <div class="row">
        @include('partials.alerts')
        <div class="col-md-12">
        <div class="card">
            <div class="card-body box-profile">

                <h3 class="profile-username text-center">#{{ $user->id }} {{ $user->name }}</h3>

                <p class="text-muted text-center">{{ $user->email }}</p>

                <ul class="list-group list-group-unbordered mb-3">
                    <li class="list-group-item">
                        <b>Status</b> <a class="float-right">{{$user->status}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Lang</b> <a class="float-right">{{$user->lang->full_name}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Creation Date</b> <a class="float-right">{{$user->created_at}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Email Verified</b> <a class="float-right">{{$user->email_verified_at}}</a>
                    </li>
                </ul>

                <a href="{{route('users.edit', ["user" => $user->id])}}" class="btn btn-primary btn-block"><b>Edit</b></a>
            </div>
            <!-- /.card-body -->
        </div>
        </div>
    </div>
@stop

@section('js')
@stop